### ISSUE TITLE
Short suggestion on package

### ISSUE THREAD

**Issue by marctang** [robince/bayesian-prevalence#1]
Hi to the authors! and thank you for providing such a great and clean materials! Really amazing job! 

I am just passing by to report a package reading issue in the R code: if I run the bayesprev_example.R file (https://github.com/robince/bayesian-prevalence/blob/master/R/bayesprev_example.R) with the supplementary data, it returns the following error at line 87, reporting the need of ```library(nleqslv)``` before running the chunk. I know this is really minor but I thought it would be good to let you guys know it too, but again, really thanks for providing such nice materials for readers to reproduce :-)

```
> int = bayesprev_hpdi(0.96, k, n)
Error in nleqslv(x_init, g, method = "Newton", control = list(maxit = 1000),  : 
  could not find function "nleqslv"
```

**Comment by robince** [comment]
Thanks very much. Loaded the libary to clean this up.
